index:
    resource: "AppBundle\Controller\HomeController"
    type: annotation

user:
    resource: "@AppBundle/Controller/UsersController.php"
    type: rest
    prefix: /api

race:
    resource: "@AppBundle/Controller/RacesController.php"
    type: rest
    prefix: /api

external_race:
    resource: "@AppBundle/Controller/ExternalRacesController.php"
    type: rest
    prefix: /api

api:
    resource: "AppBundle\Controller\TestController"
    type: rest

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"